src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latin America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Competitive_Intelligence__c.object
<CustomObject>
    <description>Database to add and store competitive intelligence data.  Originally created for Packaging.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>notEqual</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitive_Intelligence1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Category__c</fullName>
        <label>Activity/Category</label>
        <picklist>
            <picklistValues>
                <fullName>Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Run</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Bev Can</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steel Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>3M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKZO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BYK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancoat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ChaCheng</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemtool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colormatrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concorrente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diostyl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dupont</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern Coatings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eclatin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecopaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuabarnices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evipac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F&amp;H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fineshine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace Darex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henkel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mexico/Central America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_End_Use__c</fullName>
        <label>Market / End Use</label>
        <picklist>
            <picklistValues>
                <fullName>Bev Can 2PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Base Coat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Dome Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Inks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Inside Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Rimcoat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 2PC-Varnish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-Dome Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-Inks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-Inside Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-Rimcoat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-Varnish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Can 3PC-White Base Coat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End-E-Coat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End Exterior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End-Interior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End Retort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev End-Tabstock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTC-Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTC-Laminate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-2PC DRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-3PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-D&amp;I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-Exterior Varnish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-EZOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-Inside Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-Pealable Membrane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-Post Repair Spray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food-Powder</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Competitive Intel</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Comp Intel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Intel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCompIntel.cls
@istest
private  class TestCompIntel
{

static testMethod void myTest() 
{

Account testAccount = new Account(Name = 'TestAccount');
insert testAccount;

    Integer count1 = [SELECT count() from FeedItem];    
    
Competitive_Intelligence__c cc = new Competitive_Intelligence__c ();
cc.Market_End_Use__c = 'Bev Can 2PC';
cc.Topic__c = 'test topic';
cc.Detail__c = 'test Detail';
insert cc;
 
Competitive_Intelligence__c cc2 = new Competitive_Intelligence__c ();
cc2.Account_Name__c = testAccount.ID ; 
cc2.Market_End_Use__c = 'Bev Can 2PC';
cc2.Topic__c = 'test topic';
cc2.Detail__c = 'test Detail';
cc2.Competitor__c = 'Other'; // NARMIN //
cc2.Business_Segment__c = 'Bev Can'; // NARMIN //
cc2.Global_Region__c = 'All'; // NARMIN //
cc2.Activity_Category__c = 'Other'; // NARMIN //
insert cc2;    
    
    Integer count2 = [SELECT count() from FeedItem]; 

FeedItem f = new FeedItem(); 

f.ParentId = '0F9E00000008cyZ'; // NARMIN changed id to one from production //
f.Body = 'New competitive intel has been added for';
insert f; 

    System.Assert(count2 - 2 == count1);
    
}

}