src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Enter in the Account Type</description>
        <label>Account Type</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User/Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor/Jobber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Importer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Mid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lowes Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mass Merchant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Business Owner responsible for the revenue within this market segment of the BU.</description>
        <label>Business Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This field is autopopulated by a trigger that looks at the user record of the creator of the record and or the current assigned owner and uses their BU for reporting purposes.</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Consumer</businessProcess>
        <description>Consumer opportunity record type</description>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Guardsman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Huarun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Menards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestPopulateBusinessOwnerOnOpportunity.cls
@isTest
private class TestPopulateBusinessOwnerOnOpportunity {

    static testMethod void populateBusinessOwnerOnOpportunityNotNull() {
    Profile Lowes = [Select id from Profile where Name = 'Consumer Lowes Sales Managers and Marketing' limit 1];
        User u1 = new User(
            Alias = 'kirktest', 
            Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = Lowes.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='kirktest@xyz.com',
            Business_Unit__c = 'Consumer Lowes'
        );
        insert u1;
             
        User u2 = new User(
            Alias = 'xyz', 
            Email='standarduser2@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing2',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = Lowes.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='valspartest@xyz.com',
            Business_Unit__c = 'Consumer Lowes',
            ManagerID = u1.ID
        );
        insert u2;
        
    Account a1 = new Account(
      OwnerId = u2.ID,
      Name = 'Lowes of Kalamazoo',
      Account_Type__c = 'Lowes Store',
      Business_Unit__c = 'Consumer Lowes'
      );
    insert a1;
    
    Opportunity o1 = new Opportunity(
      Name = 'Opportunity 1',
      OwnerID = u2.id,
      Business_Unit__C = 'Consumer Lowes',
      AccountId = a1.id,
      CloseDate = system.today(),
      StageName = 'Qualification'
      );
      insert o1;
         
    //Check*/
    test.startTest();
      
    
    try{
        update o1;
    }catch(Exception e){
        System.debug(Logginglevel.INFO, '***** ERROR'+e.getMessage());
    }
    opportunity testopp = [select OwnerId, Business_Owner__C FROM Opportunity where Name = 'Opportunity 1']; 
    System.assertEquals(testopp.Business_Owner__C, u1.ID);
   // System.assertEquals(c1.ownerID, u2.ID);
   // System.assertEquals(c2.ownerID, u2.ID);
    //System.assertEquals(c3.ownerID, u2.ID);
   // System.assertEquals(t1.ownerID, a2.OwnerID);
    test.stopTest();
     
    }
    
}