src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Functionality_by_BU__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting to be used by Triggers, Classes and other functionality to determine for which BU the functionality will be enabled.
Enter the BU in the NAME field to match on BU in the related object.</description>
    <fields>
        <fullName>Parent_Account_Team_Creation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Functionality that will auto populate and update accordingly Account Teams on the Parent Accounts.  The Owner of each Child Account will be added to the Account Team on the Parent Account.</description>
        <label>Parent Account Team Creation</label>
        <type>Checkbox</type>
    </fields>
    <label>Functionality Enabled by Business Unit</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Guardsman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Huarun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Menards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestUpdateAccountTeam.cls
@isTest
private class TestUpdateAccountTeam
{
    static testMethod void testAccountTeams()
    {
      createCustomSettings();

      Profile standardUserProfile = [select id from profile where name='Standard User']; 

      User childOwner = new User(FirstName='Bob', LastName='Marley', Username='BobMar@valspar.com', Email='BobMarley@heyman.us', Alias='BobMar', CommunityNickname='BobMarley', TimeZoneSidKey='America/Chicago', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', ProfileId=standardUserProfile.Id, LanguageLocaleKey='en_US');
      insert childOwner ;

      Account parentAcct = new Account(Name='Test Parent Acct', Business_Unit__c = 'General Industrial');
      insert parentAcct;

      Account childAcct = new Account(Name='Test Child Acct', Business_Unit__c = 'General Industrial', ParentId = parentAcct.Id, OwnerId = childOwner.Id);
      insert childAcct;

      list<AccountTeamMember> parentAccountTeam = [SELECT UserId
                                                   FROM AccountTeamMember
                                                   WHERE AccountId = :parentAcct.id];

      system.AssertEquals(1, parentAccountTeam.size());
      system.AssertEquals(childOwner.Id, parentAccountTeam[0].UserId);
    }

    private static void createCustomSettings()
    {
      insert new Functionality_by_BU__c(Name='General Industrial', Parent_Account_Team_Creation__c = true);
    }
}