src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Manual_Account</fullName>
        <active>true</active>
        <description>Read Write Accounts in Salesforce that do not exist in Oracle</description>
        <label>Manual Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unknown_Last_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If customer does not provide last name then check the box</description>
        <inlineHelpText>If customer does not provide last name then check the box and type at least one character (&quot;x&quot; for example) into the Last Name field</inlineHelpText>
        <label>Unknown Last Name</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Valspar_Master_Contact_Record_Type</fullName>
        <active>true</active>
        <description>Master contact record type for Valspar.</description>
        <label>Valspar Master Contact Record Type</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Cloud_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Service Cloud Settings</label>
</CustomObject>

src/classes/blogic_ContactActions.cls
public class blogic_ContactActions {
/********************************************************************************	
 * CLASS
 */
	
	private static String UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_DEVELOPER_NAME = 'Valspar_Master_Contact_Record_Type'; //default, override by custom setting if exist
	private static String UNKNOWN_CONTACT_DEFAULT_LASTNAME_VALUE = 'Unknown'; //default, override by custom setting if exist

	private static String CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_DEVELOPER_NAME = 'Valspar_Master_Contact_Record_Type'; //default, override by custom setting if exist
	private static String CREATE_CONSUMER_ACCOUNT_ACT_ON_BUSINESS_UNIT = 'Consumer Consumer'; //default, override by custom setting if exist
	private static String CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_DEVELOPER_NAME = 'Manual_Account'; //default, override by custom setting if exist
	private static String CREATE_CONSUMER_ACCOUNT_BUSINESS_UNIT_VALUE = 'Consumer Consumer'; //default, override by custom setting if exist

 
    private static Id UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_ID;
    private static Id CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_ID;
    private static Id CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_ID;

	static {
	/********************************************************************************	
	 * Class-level Static Code Block
	 */

	    // Obtain the Settings from a Custom Settings Object
    	List<Service_Cloud_Settings__c> settings = Service_Cloud_Settings__c.getAll().values();
    	for (Service_Cloud_Settings__c setting : settings) {
      		if (Setting.Name == 'Unknown Contact - Act On RecordType') UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_DEVELOPER_NAME = Setting.Value__c;          
      		if (Setting.Name == 'Unknown Contact - LastName Default') UNKNOWN_CONTACT_DEFAULT_LASTNAME_VALUE = Setting.Value__c;          
      		if (Setting.Name == 'Create Account - Act On RecordType') CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_DEVELOPER_NAME = Setting.Value__c;          
      		if (Setting.Name == 'Create Account - Act On Business Unit') CREATE_CONSUMER_ACCOUNT_ACT_ON_BUSINESS_UNIT = Setting.Value__c;          
      		if (Setting.Name == 'Create Account - New RecordType Name') CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_DEVELOPER_NAME = Setting.Value__c;          
      		if (Setting.Name == 'Create Account - Business Unit Default') CREATE_CONSUMER_ACCOUNT_BUSINESS_UNIT_VALUE = Setting.Value__c;          
    	}
    	
    	//could be optimized to one query
    	UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_ID = [SELECT Id FROM RecordType WHERE DeveloperName = :UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_DEVELOPER_NAME LIMIT 1][0].Id;
    	CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_ID = [SELECT Id FROM RecordType WHERE DeveloperName = :CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_DEVELOPER_NAME LIMIT 1][0].Id;
    	CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_ID = [SELECT Id FROM RecordType WHERE DeveloperName = :CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_DEVELOPER_NAME LIMIT 1][0].Id;

	} //End Static Code Block	



	public static void PopulateLastNameOnUnknown (List<Contact> newContacts) {
	/********************************************************************************	
	 * METHOD: PopulateLastNameOnUnknown (to be called from CONTACT BEFORE INSERT)
	 */

		//Traverse all new Contact in Trigger context
		for (Contact c : newContacts) {
			if (c.Unknown_Last_Name__c == true /* && c.RecordTypeId == UNKNOWN_CONTACT_ACT_ON_RECORDTYPE_ID */ ) {
				c.LastName = UNKNOWN_CONTACT_DEFAULT_LASTNAME_VALUE; //business rule says to overwrite regardless of value
			}
		} 	
		
	} //End PopulateLastNameOnUnknown Method

	public static void CreateConsumerAccount (List<Contact> newContacts) {
	/********************************************************************************	
	 * METHOD: CreateConsumerAccount (to be called from CONTACT BEFORE INSERT)
	 */

		List<Account> accountsToAdd = new List<Account>();
		List<Contact> contactsToUpdate = new List<Contact>();

		//Traverse all new Contact in Trigger context
		for (Contact c : newContacts) {
			if (c.Business_Unit__c == CREATE_CONSUMER_ACCOUNT_ACT_ON_BUSINESS_UNIT &&
			    c.AccountId == null /* && c.RecordTypeId == CREATE_CONSUMER_ACCOUNT_ACT_ON_RECORDTYPE_ID */ ) {
				Account newConsumerAccount = new Account(RecordTypeId=CREATE_CONSUMER_ACCOUNT_NEW_RECORDTYPE_ID,
														 Name=(((c.FirstName != null) ? c.FirstName + ' ' : '') + c.LastName).trim(),
														 Business_Unit__c=CREATE_CONSUMER_ACCOUNT_BUSINESS_UNIT_VALUE);
				accountsToAdd.add(newConsumerAccount);
				contactsToUpdate.add(c);
			}
		} 	
		
		insert accountsToAdd; //to do, add pretty exception handling
		
		//update related contacts with AccountId
		Integer i = 0;
		for (Contact c : contactsToUpdate) {
			c.AccountId = accountsToAdd[i].Id;
			i++;
		}
		
	} //End CreateConsumerAccount Method


} //End blogic_ContactActions Class