src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Enter in the Account Type</description>
        <label>Account Type</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User/Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor/Jobber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Importer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Mid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lowes Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mass Merchant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Guardsman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Huarun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Menards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestUpdateChildAccountOwner.cls
@isTest(SeeAllData=true)

private class TestUpdateChildAccountOwner {

    static testMethod void updateChildAccountOwner() {
    //Create
        
        Profile Lowes = [Select id from Profile where Name = 'Consumer Lowes Sales Managers and Marketing' limit 1];
        User u1 = new User(
            Alias = 'kirktest', 
            Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = Lowes.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='kirktest@xyz.com',
            Business_Unit__c = 'Consumer Lowes'
        );
        insert u1;
             
        User u2 = new User(
            Alias = 'xyz', 
            Email='standarduser2@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing2',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = Lowes.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='valspartest@xyz.com',
            Business_Unit__c = 'Consumer Lowes'
        );
        insert u2;
        
    Account a1 = new Account(
      OwnerId = u1.ID,
      Name = 'Lowes of Kalamazoo',
      Account_Type__c = 'Lowes Store',
      Business_Unit__c = 'Consumer Lowes'
      );
    insert a1;
    
    Account a2 = new Account(
      OwnerId = u1.ID,
      Name = 'Tom Tom Painting',
      Account_Type__c = 'Pro Account',
      Business_Unit__c = 'Consumer Lowes',
      ParentID = a1.ID
      );
    insert a2;
    
    Contact c1 = new Contact(
      OwnerId = u1.ID,
      LastName = 'Smith',
      AccountID = a2.ID
      );
    Contact c2 = new Contact(
      OwnerId = u1.ID,
      LastName = 'Jones',
      AccountID = a2.ID
      );
      
    Contact c3 = new Contact(
      OwnerId = u1.ID,
      LastName = 'Williams',
      AccountID = a2.ID
      );
    insert new List<Contact>{c1, c2, c3};
        
    //Check*/
    test.startTest();
      
    a1.OwnerId = u2.ID;
    try{
        update a1;
    }catch(Exception e){
        System.debug(Logginglevel.INFO, '***** ERROR'+e.getMessage());
    }
    a2 = [select OwnerId FROM Account Where Name = 'Tom Tom Painting' Limit 1][0]; 
    System.assertEquals(a2.ownerID, u2.ID);
   // System.assertEquals(c1.ownerID, u2.ID);
   // System.assertEquals(c2.ownerID, u2.ID);
    //System.assertEquals(c3.ownerID, u2.ID);
   // System.assertEquals(t1.ownerID, a2.OwnerID);
    test.stopTest();
     
    }
    
}