src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Intelligence__c.object
<CustomObject>
    <description>For Wattyl Trade</description>
    <label>Account Intelligence</label>
    <nameField>
        <label>Account Intelligence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Intelligence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAutoCreateIntelligence.cls
@isTest
public class TestAutoCreateIntelligence{

    static testmethod void testCreateAI()
    {
        Integer count1 = [Select count() from Account_Intelligence__c];
        
    Account acc = new Account();
        acc.Name = 'test';
        acc.Business_Unit__c = 'Consumer Wattyl Trade';
        insert acc;
        
        Integer count2 = [Select count() from Account_Intelligence__c];
    
      System.AssertEquals(count1 + 1, count2);
    }
    
    static testmethod void testCreateCPAI()
    {
        Integer count3 = [Select count() from Channel_Partner_Account_Intelligence__c];
        
    Account acc = new Account();
        acc.Name = 'test';
        acc.Business_Unit__c = 'Consumer Masters';
        insert acc;
        
        Integer count4 = [Select count() from Channel_Partner_Account_Intelligence__c];
    
      System.AssertEquals(count3 + 1, count4);
    }
    
}