src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Expected_Revenue__c</fullName>
        <inlineHelpText>&quot;Enter amount of expected yearly revenue in the currency this Opportunity will be billed.&quot;</inlineHelpText>
        <label>Annual Expected Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This field is autopopulated by a trigger that looks at the user record of the creator of the record and or the current assigned owner and uses their BU for reporting purposes.</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Guardsman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Huarun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Menards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestPopulateBusinessUnitOnOpportunity.cls
@isTest
private class TestPopulateBusinessUnitOnOpportunity {

    static testMethod void populateBusinessUnitOnOpportunityNotNull() {
        
        //Create
        User u = [SELECT Id, Business_Unit__c FROM User WHERE Id = :userInfo.getUserId() LIMIT 1];
        u.Business_Unit__c = 'Automotive';
        update u;
        Account acct = new Account(Name='Test Acct');
        insert acct;
        Opportunity opp = new Opportunity(Name='Test Opp', AccountId=acct.Id, CloseDate=system.Today(), StageName='Qualification', Annual_Expected_Revenue__c=1);
        
        //Invoke
        insert opp;
        
        //Check
        Opportunity o = [SELECT Id, Business_Unit__c FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        system.assertEquals(u.Business_Unit__c, o.Business_Unit__c);
    }
    
    static testMethod void populateBusinessUnitOnOpportunityNull() {
        
        //Create
        User u = [SELECT Id, Business_Unit__c FROM User WHERE Id = :userInfo.getUserId() LIMIT 1];
        u.Business_Unit__c = NULL;
        update u;
        Account acct = new Account(Name='Test Acct');
        insert acct;
        Opportunity opp = new Opportunity(Name='Test Opp', AccountId=acct.Id, CloseDate=system.Today(), StageName='Qualification', Annual_Expected_Revenue__c=1);
        
        //Invoke
        insert opp;
        
        //Check
        Opportunity o = [SELECT Id, Business_Unit__c FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        system.assertEquals(u.Business_Unit__c, o.Business_Unit__c);
    }
}