src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latin America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Fiscal_Period__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>North America End Date</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>Fiscal_Year__c</referenceTo>
        <relationshipLabel>Fiscal Periods</relationshipLabel>
        <relationshipName>Fiscal_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROW_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ROW_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>North America Period Start Date</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Fiscal Period</label>
    <nameField>
        <label>Fiscal Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Fiscal_Year__c.object
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Expected_Revenue__c</fullName>
        <inlineHelpText>&quot;Enter amount of expected yearly revenue in the currency this Opportunity will be billed.&quot;</inlineHelpText>
        <label>Annual Expected Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity Closed Date will autopopulate the respective Fiscal Period the business is projected to be closed.</description>
        <inlineHelpText>CALCULATED: Valspar Fiscal Period based on Close Date and Valspar entity
the Opportunity Owner belongs--e.g. North American Opportunity
Owners use the 4-4-5 fiscal calendar or International for monthly fiscal
calendar.</inlineHelpText>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Period__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latin America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <label>Reason Won/Lost</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>No Decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service &amp; Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Selection</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestSetFiscalPeriodOnOpportunity.cls
@isTest
private class TestSetFiscalPeriodOnOpportunity {

    static testMethod void setFiscalPeriodOnOpportunityNA() {
        //Create
        list<Fiscal_Period__c> fpToDelete = new list<Fiscal_Period__c>();
        list<Fiscal_Period__c> fpList = new list<Fiscal_Period__c>();
		
        
        //gwinkel add fp 02/04/2014
        Fiscal_Period__c fp = new Fiscal_Period__c();
        fp.Name = 'test';
        fp.CurrencyIsoCode = 'USD';
        fp.Start_Date__c = system.today().addDays(-30);
        fp.End_Date__c = system.today().addDays(30);
        fp.ROW_Start_Date__c = system.today().addDays(-30);
        fp.ROW_End_Date__c = system.today().addDays(30);
		fpList.add(fp);
        /*
        Fiscal_Period__c fp2 = new Fiscal_Period__c();
        fp2.Name = 'test';
        fp2.CurrencyIsoCode = 'USD';
        fp2.Start_Date__c = system.today().addDays(-30);
        fp2.End_Date__c = system.today().addDays(30);
        fp2.ROW_Start_Date__c = system.today().addDays(-30);
        fp2.ROW_End_Date__c = system.today().addDays(30);
        fpList.add(fp2);
        */
        insert fpList;
        /*
        for (Fiscal_Period__c fp : [SELECT Id
                                    FROM Fiscal_Period__c
                                    WHERE Start_Date__c >= :system.today().addYears(-1)
                                      AND End_Date__c <= :system.today().addYears(1)])
        {
            fpToDelete.add(fp);
        }
        delete fpToDelete;
		*/
        /*
        String fyName = String.valueOf(system.Today().year());

        Fiscal_Year__c testYear = new Fiscal_Year__c(Name='TestYear', 
                                                   Start_Date__c=system.Today(),
                                                   End_Date__c=system.Today().addDays(30),
                                                   Fiscal_Year__c=fy.Id);
        
        Fiscal_Year__c fy = [SELECT Id
                             FROM Fiscal_Year__c
                             WHERE Name = :fyName 
                             LIMIT 1];
*/		
/*
        Fiscal_Period__c fp = new Fiscal_Period__c(Name='TestPeriod 1 - ' + system.Today().year(), 
                                                   Start_Date__c=system.Today(),
                                                   End_Date__c=system.Today().addDays(30),
                                                   Fiscal_Year__c=fy.Id);
        fpList.add(fp);
        Fiscal_Period__c fp2 = new Fiscal_Period__c(Name='TestPeriod 2 - ' + system.Today().year(), 
                                                    Start_Date__c=system.Today().addDays(31),
                                                    End_Date__c=system.Today().addDays(60),
                                                    Fiscal_Year__c=fy.Id);
        fpList.add(fp2);
        */
        
        //insert fpList;

        Account a = new Account(Name='Test');
        insert a;

        Opportunity o = new Opportunity(Name='Test',
                                        AccountId=a.Id,
                                        CloseDate=Date.Today().addDays(15), 
                                        StageName='Qualification',
                                        Annual_Expected_Revenue__c=1,
                                        Global_Region__c = 'North America');
        //Invoke
        insert o;
		System.debug('Opp Insert:' + o.Fiscal_Period__c);
        //o.StageName = 'Closed';
        //update o;
        
        //Check
        Opportunity testOpp = [SELECT Id,
                               Fiscal_Period__c
                               FROM Opportunity
                               WHERE Name = 'Test'
                               LIMIT 1][0];
        
        //Invoke Close Functionality
        o.StageName = 'Closed/Won';
        o.Reason_Won_Lost__c = 'No Decision';
        update o;
		System.debug('Opp Update:' + o.Fiscal_Period__c);
        //Check
        Opportunity testOpp2 = [SELECT Id, Fiscal_Period__c
                                FROM Opportunity
                                WHERE Name = 'Test'
                                LIMIT 1][0];

        system.assertEquals(fp.Id, testOpp2.Fiscal_Period__c);
    }

    static testMethod void setFiscalPeriodOnOpportunityROW() {
        //Create
        list<Fiscal_Period__c> fpToDelete = new list<Fiscal_Period__c>();
        list<Fiscal_Period__c> fpList = new list<Fiscal_Period__c>();

        //gwinkel add fp 02/04/2014
        Fiscal_Period__c fp = new Fiscal_Period__c();
        fp.Name = 'test';
        fp.CurrencyIsoCode = 'USD';
        fp.Start_Date__c = system.today().addDays(-30);
        fp.End_Date__c = system.today().addDays(30);
        fp.ROW_Start_Date__c = system.today().addDays(-30);
        fp.ROW_End_Date__c = system.today().addDays(30);
		fpList.add(fp);
        /*
        Fiscal_Period__c fp2 = new Fiscal_Period__c();
        fp2.Name = 'test';
        fp2.CurrencyIsoCode = 'USD';
        fp2.Start_Date__c = system.today().addDays(-30);
        fp2.End_Date__c = system.today().addDays(30);
        fp2.ROW_Start_Date__c = system.today().addDays(-30);
        fp2.ROW_End_Date__c = system.today().addDays(30);
        fpList.add(fp2);
        */
        insert fpList;
        
        /*
        for (Fiscal_Period__c fp : [SELECT Id
                                    FROM Fiscal_Period__c
                                    WHERE ROW_Start_Date__c >= :system.today().addYears(-1)
                                      AND ROW_End_Date__c <= :system.Today().addYears(1)])
        {
            fpToDelete.add(fp);
        }
        delete fpToDelete;

        String fyName = String.valueOf(system.Today().year());

        Fiscal_Year__c fy = [SELECT Id
                             FROM Fiscal_Year__c
                             WHERE Name = :fyName 
                             LIMIT 1];

        Fiscal_Period__c fp = new Fiscal_Period__c(Name='TestPeriod 1 - ' + system.Today().year(),
                                                   Start_Date__c=system.Today().addYears(-1),
                                                   End_Date__c=system.Today().addYears(-1),
                                                   ROW_Start_Date__c=system.Today(),
                                                   ROW_End_Date__c=system.Today().addDays(30),
                                                   Fiscal_Year__c=fy.Id);
        fpList.add(fp);
        Fiscal_Period__c fp2 = new Fiscal_Period__c(Name='TestPeriod 2 - ' + system.Today().year(), 
                                                    Start_Date__c=system.Today().addYears(-1),
                                                    End_Date__c=system.Today().addYears(-1),
                                                    ROW_Start_Date__c=system.Today().addDays(31),
                                                    ROW_End_Date__c=system.Today().addDays(60),
                                                    Fiscal_Year__c=fy.Id);
        fpList.add(fp2);
        insert fpList;
		*/
        Account a = new Account(Name='Test');
        insert a;

        Opportunity o = new Opportunity(Name='Test',
                                        AccountId=a.Id,
                                        CloseDate=system.Today(), 
                                        StageName='Qualification',
                                        Annual_Expected_Revenue__c=1,
                                        Global_Region__c = 'EMEAI');
        //Invoke
        insert o;

        //Check
        Opportunity testOpp = [SELECT Id,
                               Fiscal_Period__c
                               FROM Opportunity
                               WHERE Id = :o.Id
                               LIMIT 1];

        system.assertEquals(fp.Id, testOpp.Fiscal_Period__c);

        //Invoke Close Functionality
        o.StageName = 'Closed/Won';
        o.Reason_Won_Lost__c = 'No Decision';
        update o;

        //Check
        Opportunity testOpp2 = [SELECT Id, Fiscal_Period__c
                                FROM Opportunity
                                WHERE Id = :o.Id
                                LIMIT 1];

        system.assertEquals(fp.Id, testOpp2.Fiscal_Period__c);
    }
}