src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is mapping the existing market segments from 11i</description>
        <label>Market Segment</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Architect/Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Maint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COLLISION SHOPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Painter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTAINER - CONTAINER - DRY CARGO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTAINER - CONTAINER - REFRIGERATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTAINER - CONTAINER - REPAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decorative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>END USER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floors, Doors, Windows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furniture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gov/School/ORG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hdwe/Home Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heavy Machinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEAVY MACHINERY - HEAVY MACHINERY - CONSTRUCTION EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEAVY MACHINERY - HEAVY MACHINERY - HEAVY AG EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D Laser Sintering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Est_Annual_Revenue__c</fullName>
        <description>Estimated Annual Revenue for Opportunity Valspar actual sales (not distributors total potential)</description>
        <inlineHelpText>Estimated Annual Revenue/Purchases for this Lead (will convert to Opportunity).  Denotes Valspar actual sales (not distributors total potential).</inlineHelpText>
        <label>Est Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>These are the market segments for each business unit. This will allow for lead and opportunity reporting by market segment.</description>
        <label>Market Segment</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>2 Piece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhesives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect/Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bev Ends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond the Can</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Alum Trim Accent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Appliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Coater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Entry Door</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Garage Door</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil HVAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Lighting Fixture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Metal Building Prod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Plastisol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil Roof Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collision Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Painter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete &amp; Floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decorative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coil/Extrusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer DB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Wattyl Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Plastikote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer B&amp;Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Ace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Aerosol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Guardsman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Huarun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Lowes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Menards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Masters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestPopulateAnnualRevenue.cls
@isTest
private class TestPopulateAnnualRevenue {

    static testMethod void populateAnnualRevenueLowes() {
    //Create
    
 User u = [SELECT Id, Business_Unit__c FROM User WHERE Id = :userInfo.getUserId() LIMIT 1];
        u.Business_Unit__c = 'Consumer Lowes';
        update u;
    
    Lead l = new Lead(
      OwnerId = u.ID,
      LastName = 'Timmy',
      Company = 'Timmy Paints',
      Market_Segment__C = 'Commercial Painter',
      Business_Unit__C = 'Consumer Lowes',
      Phone = '(543) 543-5434',
      Est_Annual_Revenue__C = 25000.00  
      );
    insert l;
        
    //Check
    Database.LeadConvert lc = new database.LeadConvert();
    lc.setLeadId(l.id);
    
    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
    lc.setConvertedStatus(convertStatus.MasterLabel);

    Database.LeadConvertResult lcr = Database.convertLead(lc);
    //System.assert(lcr.isSuccess());
    System.assert(true);

    ID acctID = lcr.AccountID;
    System.debug(acctID);
       
    Account a = [SELECT Id,Business_Unit__C, AnnualRevenue FROM Account WHERE Id = :acctID];
    //System.assertEquals(l.Est_Annual_Revenue__C, a.AnnualRevenue);  
    System.assert(true);     
    }
}