src/objects/Case_Product_Information__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Product Information</relationshipLabel>
        <relationshipName>Case_Product_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>New custom Item Number field</description>
        <label>Item Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Product Information</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>CPI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CPI11iBatchItemCallTrg_test.cls
@istest(seeAlldata=true)
public class CPI11iBatchItemCallTrg_test{
public static testmethod void testCPI11iBatchItemCallTrg()
{
case c=new case(subject='test case',Channel__c='Ace',   Brand__c='valspar',type='product');
insert c;
Case_Product_Information__c cp=new  Case_Product_Information__c(Case__c=c.id,   Item_Number__c='123456789123456');
insert cp;
cp.Item_Number__c='123456789123457';
update cp;
}
}