src/objects/Curriculum__c.object
<CustomObject>
    <label>Training Curriculum</label>
    <nameField>
        <label>Training Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Curriculum</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training__c.object
<CustomObject>
    <description>Training object for consumer.  Contains training module information and training tracking information.</description>
    <fields>
        <fullName>Assortment__c</fullName>
        <description>Training family</description>
        <label>Assortment</label>
        <picklist>
            <picklistValues>
                <fullName>Bulk Paint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Coatings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabot Stains</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Aerosols</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceiling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exterior Paints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Features &amp; Effects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Paints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metal Paint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint Foundations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pascol Paving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Woodcare</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Curriculum__c.object
<CustomObject>
    <description>The association between Training Courses and Training Curriculum (M:M relationship)</description>
    <fields>
        <fullName>Curriculum__c</fullName>
        <label>Training Curriculum</label>
        <referenceTo>Curriculum__c</referenceTo>
        <relationshipLabel>Training Curriculum Courses</relationshipLabel>
        <relationshipName>Training_Curriculum</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <label>Training Courses</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Training Curriculum Courses</relationshipLabel>
        <relationshipName>Training_Curriculum</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Curriculum Courses</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Training Curriculum Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Curriculum Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrainingTaskLogicTest.cls
// *********************************************************************************************
// Filename:        TrainingTaskLogicTest
// Author:          Etherios Inc.
// Date Created:    7/22/2014
// Description:     TrainingTaskLogicTest handles all test cases for the TrainingTaskLogic class
//                  
//
// Date     | Name                          | Task#     | Comments
// --------------------------------------------------------------------------------------------
// 7/11/2014   |jwhittington@etherios.com          |           |File creation
// --------------------------------------------------------------------------------------------
// 
// Copyright 2014 Etherios Inc. All rights reserved. Customer confidential. Do not distribute.
// *********************************************************************************************
// *********************************************************************************************
@isTest
public class TrainingTaskLogicTest {
    static testMethod void testTaskTrigger(){
        Account account1 = new Account(name='test account');
        insert account1;
        
        Contact[] contactsToCreate = new Contact[]{};
        
        Contact contact1 = new Contact(AccountId=account1.Id,lastname='testing1',firstname='apex');
        insert contact1;
        
        Curriculum__c curriculum = new Curriculum__c(Name='Testing');
        insert curriculum;
        
        Training__c[] trainingToCreate = new Training__c[]{};
        for (Integer x=0; x<5;x++) {
            Training__c training = new Training__c(Name='Training Test '+x,Category__c='Test',Assortment__c='Test');
            trainingToCreate.add(training);
        }
        insert trainingToCreate;
        
        Training_Curriculum__c[] trainingCurriculumToCreate = new Training_Curriculum__c[]{};
        for (Training__c training : trainingToCreate) {
            Training_Curriculum__c trainingCurriculum = new Training_Curriculum__c(Training__c=training.Id, Curriculum__c=curriculum.Id);
            trainingCurriculumToCreate.add(trainingCurriculum);
        }
        insert trainingCurriculumToCreate;

        Task[] tasksToCreate = new Task[]{};
        for (Integer x=0; x<200; x++) {
            Task t = new Task(RecordTypeId='012E00000002D8Y',Subject='Testing',WhatId=curriculum.Id,WhoId=contact1.Id,Activity_Type__c='Training Curriculum',Training_Type__c='Aisle');
            tasksToCreate.add(t);
        }
        System.debug(tasksToCreate.size());
                
        //Now insert data causing an contact trigger to fire. 
        Test.startTest();
        insert tasksToCreate;
        Test.stopTest();
    }   
}